package app.ui.banco;

import app.modello.Elemento;
import app.modello.Etichetta;
import app.modello.Tipo;
import app.render.Disegno;
import app.render.Ingombri;
import app.render.SorgenteQr;
import app.stile.Stile;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/** Canvas con spostamento e ridimensionamento diretto. */
public class Foglio extends JComponent {
    public interface Ascolto{void selezionato(Elemento e);void staPerCambiare();void modificato();}
    private enum Angolo{NO,NW,NE,SW,SE}
    private final SorgenteQr qr;private Etichetta eti;private Elemento selezione;private double mmPx=6;private Ascolto ascolto;private Map<Elemento,Rectangle2D.Double> ingombri;private Point presa;private double presaX,presaY;private boolean adattato,trascinato;private Angolo ridimensiona=Angolo.NO;private Rectangle2D.Double presaIngombro;private double presaLarghezza,presaAltezza,presaCorpo;
    public Foglio(Etichetta eti,SorgenteQr qr){this.eti=eti;this.qr=qr;setBackground(Stile.BANCO);setOpaque(true);setFocusable(true);mouse();tasti();}
    public void ascolto(Ascolto a){ascolto=a;}public Etichetta etichetta(){return eti;}public void etichetta(Etichetta e){eti=e;selezione=e.elementi().isEmpty()?null:e.elementi().get(0);revalidate();repaint();}public Elemento selezione(){return selezione;}public void selezione(Elemento e){selezione=e;if(ascolto!=null)ascolto.selezionato(e);repaint();}public double zoom(){return mmPx;}public int percentuale(){return(int)Math.round(mmPx/(96.0/25.4)*100);}public void zoomPasso(int s){percentuale(percentuale()+s*20);}public void percentuale(double p){double l=Math.max(30,Math.min(600,p));mmPx=l/100.0*(96.0/25.4);revalidate();repaint();}
    public void adatta(Dimension spazio){if(spazio==null||spazio.width<=0||spazio.height<=0)return;double w=spazio.width-2*margine()-righello(),h=spazio.height-2*margine()-righello(),k=Math.min(w/eti.larghezza(),h/eti.altezza());if(k>.5){mmPx=k;adattato=true;}}public void adattaEImpagina(Dimension spazio){adatta(spazio);revalidate();repaint();}private int margine(){return Stile.px(26);}private int righello(){return Stile.px(18);}private int originaX(){int larga=(int)Math.round(eti.larghezza()*mmPx),avanza=getWidth()-righello()-larga;return righello()+Math.max(margine(),avanza/2);}private int originaY(){int alta=(int)Math.round(eti.altezza()*mmPx),avanza=getHeight()-righello()-alta;return righello()+Math.max(margine(),avanza/2);}
    @Override public Dimension getPreferredSize(){return new Dimension((int)Math.round(eti.larghezza()*mmPx)+righello()+2*margine(),(int)Math.round(eti.altezza()*mmPx)+righello()+2*margine());}
    @Override protected void paintComponent(Graphics g){if(!adattato&&getParent()!=null&&getParent().getWidth()>0)adatta(getParent().getSize());Graphics2D g2=Stile.liscio(g);try{g2.setColor(Stile.BANCO);g2.fillRect(0,0,getWidth(),getHeight());int ox=originaX(),oy=originaY(),w=(int)Math.round(eti.larghezza()*mmPx),h=(int)Math.round(eti.altezza()*mmPx);righelli(g2,ox,oy,w,h);g2.setColor(new Color(0,0,0,34));g2.fillRect(ox+2,oy+3,w,h);Graphics2D gc=(Graphics2D)g2.create(ox,oy,w,h);try{Disegno.disegna(gc,eti,mmPx,qr,0);}finally{gc.dispose();}g2.setColor(Stile.S1);g2.drawRect(ox,oy,w-1,h-1);griglia(g2,ox,oy,w,h);ingombri=Ingombri.calcola(g2,eti,mmPx,0);if(selezione!=null&&ingombri.containsKey(selezione))maniglie(g2,ox,oy,ingombri.get(selezione));}finally{g2.dispose();}}
    private void righelli(Graphics2D g,int ox,int oy,int w,int h){int r=righello();g.setColor(Stile.MANTLE);g.fillRect(ox,oy-r,w,r);g.fillRect(ox-r,oy,r,h);g.setColor(Stile.S0);g.drawRect(ox,oy-r,w,r);g.drawRect(ox-r,oy,r,h);int passo=mmPx<4?5:1;g.setFont(Stile.mono(8));for(int mm=0;mm<=(int)eti.larghezza();mm+=passo){int x=ox+(int)Math.round(mm*mmPx);boolean grande=mm%10==0;g.setColor(Stile.OV0);g.drawLine(x,oy-r,x,oy-r+(grande?Stile.px(9):Stile.px(5)));if(grande&&mm>0){g.setColor(Stile.OV1);g.drawString(String.valueOf(mm),x+2,oy-Stile.px(3));}}for(int mm=0;mm<=(int)eti.altezza();mm+=passo){int y=oy+(int)Math.round(mm*mmPx);boolean grande=mm%10==0;g.setColor(Stile.OV0);g.drawLine(ox-r,y,ox-r+(grande?Stile.px(9):Stile.px(5)),y);if(grande&&mm>0){g.setColor(Stile.OV1);g.drawString(String.valueOf(mm),ox-r+Stile.px(9),y+Stile.px(7));}}}
    private void griglia(Graphics2D g,int ox,int oy,int w,int h){Graphics2D g2=(Graphics2D)g.create();try{g2.clipRect(ox,oy,w,h);Color fine=new Color(40,52,72,30),forte=new Color(40,52,72,72);for(int mm=1;mm<eti.larghezza();mm++){int x=ox+(int)Math.round(mm*mmPx);g2.setColor(mm%5==0?forte:fine);g2.drawLine(x,oy,x,oy+h);}for(int mm=1;mm<eti.altezza();mm++){int y=oy+(int)Math.round(mm*mmPx);g2.setColor(mm%5==0?forte:fine);g2.drawLine(ox,y,ox+w,y);}}finally{g2.dispose();}}
    private void maniglie(Graphics2D g,int ox,int oy,Rectangle2D.Double r){int x=ox+(int)Math.round(r.x*mmPx),y=oy+(int)Math.round(r.y*mmPx),w=(int)Math.round(r.width*mmPx),h=(int)Math.round(r.height*mmPx);g.setColor(Stile.BLU);g.setStroke(new BasicStroke(1.7f));g.drawRect(x-2,y-2,w+4,h+4);g.setStroke(new BasicStroke(1));int m=Math.max(Stile.px(9),9);maniglia(g,x-2,y-2,m);maniglia(g,x+w+2,y-2,m);maniglia(g,x-2,y+h+2,m);maniglia(g,x+w+2,y+h+2,m);}private void maniglia(Graphics2D g,int cx,int cy,int lato){g.setColor(Color.WHITE);g.fillRect(cx-lato/2,cy-lato/2,lato,lato);g.setColor(Stile.BLU);g.setStroke(new BasicStroke(1.5f));g.drawRect(cx-lato/2,cy-lato/2,lato-1,lato-1);}
    private void mouse(){MouseAdapter m=new MouseAdapter(){@Override public void mousePressed(MouseEvent ev){requestFocusInWindow();Angolo h=angoloSotto(ev.getX(),ev.getY());if(h!=Angolo.NO&&selezione!=null){preparaRidimensionamento(ev.getPoint(),h);return;}Elemento sotto=sotto(ev.getX(),ev.getY());if(sotto!=selezione)selezione(sotto);if(sotto!=null){presa=ev.getPoint();presaX=sotto.x();presaY=sotto.y();trascinato=false;ridimensiona=Angolo.NO;}}@Override public void mouseReleased(MouseEvent ev){presa=null;ridimensiona=Angolo.NO;presaIngombro=null;aggiornaCursore(ev);}@Override public void mouseDragged(MouseEvent ev){if(presa==null||selezione==null)return;if(!trascinato){trascinato=true;if(ascolto!=null)ascolto.staPerCambiare();}if(ridimensiona!=Angolo.NO)ridimensionaA(ev.getX(),ev.getY());else muovi(presaX+(ev.getX()-presa.x)/mmPx,presaY+(ev.getY()-presa.y)/mmPx);}@Override public void mouseMoved(MouseEvent ev){aggiornaCursore(ev);}@Override public void mouseExited(MouseEvent ev){if(presa==null)setCursor(Cursor.getDefaultCursor());}};addMouseListener(m);addMouseMotionListener(m);}
    private void preparaRidimensionamento(Point p,Angolo h){presa=p;ridimensiona=h;presaIngombro=ingombri==null?null:copia(ingombri.get(selezione));presaLarghezza=selezione.larghezza();presaAltezza=selezione.altezza();presaCorpo=selezione.corpo();trascinato=false;}
    private void ridimensionaA(int px,int py){if(presaIngombro==null||selezione==null)return;double mx=snap((px-originaX())/mmPx),my=snap((py-originaY())/mmPx),sx=presaIngombro.x,sy=presaIngombro.y,ex=sx+presaIngombro.width,ey=sy+presaIngombro.height;double left=ridimensiona==Angolo.NW||ridimensiona==Angolo.SW?limita(mx,0,ex-1):sx,right=ridimensiona==Angolo.NE||ridimensiona==Angolo.SE?limita(mx,left+1,eti.larghezza()):ex,top=ridimensiona==Angolo.NW||ridimensiona==Angolo.NE?limita(my,0,ey-.4):sy,bottom=ridimensiona==Angolo.SW||ridimensiona==Angolo.SE?limita(my,top+.4,eti.altezza()):ey;double vw=Math.max(1,right-left),vh=Math.max(.4,bottom-top);boolean scambia=selezione.rotazione()==90||selezione.rotazione()==270;double scalaL=scambia?vh/Math.max(.4,presaIngombro.height):vw/Math.max(1,presaIngombro.width),scalaH=scambia?vw/Math.max(1,presaIngombro.width):vh/Math.max(.4,presaIngombro.height);if(selezione.tipo()==Tipo.QR){double s=Math.max(.15,Math.max(scalaL,scalaH));selezione.larghezza(presaLarghezza*s);}else{selezione.larghezza(presaLarghezza*Math.max(.15,scalaL));if(selezione.tipo()==Tipo.BARCODE||selezione.tipo()==Tipo.LINEA)selezione.altezza(presaAltezza*Math.max(.15,scalaH));else if(selezione.tipo().scritto())selezione.corpo(presaCorpo*Math.max(.35,scalaH));}Rectangle2D.Double dopo=ingombroCorrente(selezione);selezione.x(snap(ridimensiona==Angolo.NW||ridimensiona==Angolo.SW?ex-dopo.width:sx));selezione.y(snap(ridimensiona==Angolo.NW||ridimensiona==Angolo.NE?ey-dopo.height:sy));rientra(selezione);avvisa();}
    private void aggiornaCursore(MouseEvent ev){Angolo h=angoloSotto(ev.getX(),ev.getY());int c;if(h==Angolo.NW||h==Angolo.SE)c=Cursor.NW_RESIZE_CURSOR;else if(h==Angolo.NE||h==Angolo.SW)c=Cursor.NE_RESIZE_CURSOR;else if(sotto(ev.getX(),ev.getY())!=null)c=Cursor.MOVE_CURSOR;else c=Cursor.DEFAULT_CURSOR;setCursor(Cursor.getPredefinedCursor(c));}
    private Angolo angoloSotto(int px,int py){if(selezione==null||ingombri==null)return Angolo.NO;Rectangle2D.Double r=ingombri.get(selezione);if(r==null)return Angolo.NO;int ox=originaX(),oy=originaY(),x1=ox+(int)Math.round(r.x*mmPx)-2,y1=oy+(int)Math.round(r.y*mmPx)-2,x2=ox+(int)Math.round((r.x+r.width)*mmPx)+2,y2=oy+(int)Math.round((r.y+r.height)*mmPx)+2,t=Math.max(7,Stile.px(8));if(vicino(px,py,x1,y1,t))return Angolo.NW;if(vicino(px,py,x2,y1,t))return Angolo.NE;if(vicino(px,py,x1,y2,t))return Angolo.SW;if(vicino(px,py,x2,y2,t))return Angolo.SE;return Angolo.NO;}
    private static boolean vicino(int px,int py,int x,int y,int t){return Math.abs(px-x)<=t&&Math.abs(py-y)<=t;}private double snap(double v){return Math.round(v*2)/2.0;}private static double limita(double v,double min,double max){return Math.max(min,Math.min(max,v));}private static Rectangle2D.Double copia(Rectangle2D.Double r){return r==null?null:new Rectangle2D.Double(r.x,r.y,r.width,r.height);}
    private void muovi(double nx,double ny){if(selezione==null)return;Rectangle2D.Double r=ingombroCorrente(selezione);double maxX=Math.max(0,eti.larghezza()-r.width),maxY=Math.max(0,eti.altezza()-r.height);selezione.x(snap(Math.max(0,Math.min(maxX,nx))));selezione.y(snap(Math.max(0,Math.min(maxY,ny))));if(ascolto!=null)ascolto.modificato();repaint();}
    public void ruotaEtichetta(){double vecchiaAltezza=eti.altezza();java.util.Map<Elemento,Rectangle2D.Double> prima=new java.util.LinkedHashMap<Elemento,Rectangle2D.Double>();for(Elemento e:eti.elementi())prima.put(e,ingombroCorrente(e));eti.scambiaLati();for(Elemento e:eti.elementi()){Rectangle2D.Double r=prima.get(e);e.x(vecchiaAltezza-(r.y+r.height));e.y(r.x);e.rotazione(e.rotazione()+90);rientra(e);}revalidate();repaint();}
    public void rientra(Elemento e){if(e==null)return;Rectangle2D.Double r=ingombroCorrente(e);double maxX=Math.max(0,eti.larghezza()-r.width),maxY=Math.max(0,eti.altezza()-r.height);e.x(Math.max(0,Math.min(maxX,e.x())));e.y(Math.max(0,Math.min(maxY,e.y())));}
    private Rectangle2D.Double ingombroCorrente(Elemento e){java.awt.image.BufferedImage img=new java.awt.image.BufferedImage(4,4,java.awt.image.BufferedImage.TYPE_INT_ARGB);Graphics2D g=img.createGraphics();try{return Ingombri.di(g,eti,e,Math.max(1,mmPx),0);}finally{g.dispose();}}
    private Elemento sotto(int px,int py){if(ingombri==null)return null;double mx=(px-originaX())/mmPx,my=(py-originaY())/mmPx;List<Elemento> pila=new ArrayList<Elemento>(eti.elementi());for(int i=pila.size()-1;i>=0;i--){Rectangle2D.Double r=ingombri.get(pila.get(i));if(r!=null&&r.contains(mx,my))return pila.get(i);}return null;}
    private void tasti(){lega("R",new AbstractAction(){@Override public void actionPerformed(ActionEvent e){if(selezione!=null){if(ascolto!=null)ascolto.staPerCambiare();selezione.rotazione(selezione.rotazione()+90);rientra(selezione);avvisa();}}});freccia("LEFT",-1,0);freccia("RIGHT",1,0);freccia("UP",0,-1);freccia("DOWN",0,1);}
    private void freccia(String tasto,final int dx,final int dy){lega(tasto,new AbstractAction(){@Override public void actionPerformed(ActionEvent e){if(selezione!=null){if(ascolto!=null)ascolto.staPerCambiare();muovi(selezione.x()+dx*.5,selezione.y()+dy*.5);}}});lega("shift "+tasto,new AbstractAction(){@Override public void actionPerformed(ActionEvent e){if(selezione!=null){if(ascolto!=null)ascolto.staPerCambiare();selezione.x(selezione.x()+dx*.1);selezione.y(selezione.y()+dy*.1);rientra(selezione);avvisa();}}});}
    private void lega(String tasto,AbstractAction a){getInputMap(WHEN_FOCUSED).put(KeyStroke.getKeyStroke(tasto),tasto);getActionMap().put(tasto,a);}private void avvisa(){if(ascolto!=null)ascolto.modificato();repaint();}
}
