package app.ui.banco;

import app.codice.Code128;
import app.codice.Correzione;
import app.codice.Qr;
import app.modello.Campo;
import app.modello.Comportamento;
import app.modello.Elemento;
import app.modello.Etichetta;
import app.modello.Serie;
import app.modello.Tipo;
import app.stile.Stile;
import app.ui.comp.Bottone;
import app.ui.comp.CodiceView;
import app.ui.comp.Scheda;
import app.ui.dati.NomiDati;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/** Inspector semplice: scelte quotidiane prima, misure precise solo su richiesta. */
public class Proprieta extends JPanel implements javax.swing.Scrollable {
    private final Runnable dopo,prima; private boolean silenzio,mostraPrecisione;
    public Proprieta(Runnable prima,Runnable dopo){this.prima=prima;this.dopo=dopo;setBackground(Stile.BASE);setLayout(new BoxLayout(this,BoxLayout.Y_AXIS));setBorder(BorderFactory.createEmptyBorder(Stile.px(18),Stile.px(16),Stile.px(18),Stile.px(16)));}
    @Override public Dimension getPreferredScrollableViewportSize(){return getPreferredSize();}
    @Override public int getScrollableUnitIncrement(java.awt.Rectangle r,int o,int d){return Stile.px(24);}
    @Override public int getScrollableBlockIncrement(java.awt.Rectangle r,int o,int d){return Stile.px(220);}
    @Override public boolean getScrollableTracksViewportWidth(){return true;}
    @Override public boolean getScrollableTracksViewportHeight(){return false;}
    public void mostra(final Etichetta eti,final Elemento e){removeAll();if(e==null){JLabel h=new JLabel("Seleziona un elemento");h.setFont(Stile.forte());h.setForeground(Stile.SUB0);h.setAlignmentX(Component.LEFT_ALIGNMENT);add(h);JLabel n=new JLabel("Poi trascinalo, ridimensionalo o ruotalo direttamente sull'etichetta.");n.setFont(Stile.piccolo());n.setForeground(Stile.OV1);n.setAlignmentX(Component.LEFT_ALIGNMENT);add(Scheda.spazio(6));add(n);revalidate();repaint();return;}silenzio=true;try{add(titolo(eti,e));add(Scheda.spazio(14));if(e.tipo()!=Tipo.LINEA){add(dati(eti,e));add(Scheda.spazio(12));}if(e.tipo().scritto()){add(testo(e));add(Scheda.spazio(12));}if(e.tipo()==Tipo.QR){add(lettura(eti,e));add(Scheda.spazio(12));}if(e.tipo()==Tipo.BARCODE){add(barre(eti,e));add(Scheda.spazio(12));}add(posizione(eti,e));add(javax.swing.Box.createVerticalGlue());}finally{silenzio=false;}revalidate();repaint();}
    private Component titolo(Etichetta eti,Elemento e){JPanel wrap=new JPanel();wrap.setOpaque(false);wrap.setLayout(new BoxLayout(wrap,BoxLayout.Y_AXIS));wrap.setAlignmentX(Component.LEFT_ALIGNMENT);JPanel p=new JPanel(new FlowLayout(FlowLayout.LEFT,Stile.px(8),0));p.setOpaque(false);p.setAlignmentX(Component.LEFT_ALIGNMENT);JLabel n=new JLabel(e.nome());n.setFont(Stile.titolo());n.setForeground(Stile.TESTO);p.add(n);p.add(new Badge(e.tipo().etichetta(),Stile.BLU_SOFT,Stile.BLU));wrap.add(p);Campo c=eti.campo(e.campo());if(c!=null){JTextArea sub=testoSecondario(NomiDati.nome(eti,c)+"  ·  "+NomiDati.uso(eti,c));sub.setBorder(BorderFactory.createEmptyBorder(Stile.px(5),Stile.px(2),0,0));wrap.add(sub);}return wrap;}
    private Component dati(final Etichetta eti,final Elemento e){Scheda s=new Scheda("Codice");s.setAlignmentX(Component.LEFT_ALIGNMENT);final Campo c=eti.campo(e.campo());if(c==null){s.nota("Questo elemento non ha ancora un codice.");return s;}final JTextField valore=new JTextField(valoreVisibile(c),18);preparaCampo(valore);valore.setToolTipText("Valore vero usato anche da QR e barcode");Runnable salvaValore=new Runnable(){@Override public void run(){if(!silenzio)applicaValore(eti,e,c,valore);}};valore.addActionListener(a->salvaValore.run());valore.addFocusListener(new FocusAdapter(){@Override public void focusLost(FocusEvent ev){salvaValore.run();}});s.campo(c.comportamento()==Comportamento.PROGRESSIVO?"Codice iniziale":"Contenuto",valore);
        final JComboBox<Campo> collega=new JComboBox<Campo>();for(Campo x:eti.campi())collega.addItem(x);collega.setSelectedItem(c);collega.setFont(Stile.normale());collega.setRenderer(new CampoRenderer(eti));collega.setPreferredSize(new Dimension(Stile.px(210),Stile.px(36)));collega.setToolTipText("Scegli un codice gia' usato da un altro elemento");collega.addActionListener(a->{if(!silenzio&&collega.getSelectedItem()!=null){segna();Campo x=(Campo)collega.getSelectedItem();e.campo(x.nome());mostra(eti,e);cambiato();}});s.campo("Usa lo stesso codice di",collega);
        final JComboBox<Comportamento> come=new JComboBox<Comportamento>(Comportamento.values());come.setSelectedItem(c.comportamento());come.setFont(Stile.normale());come.setPreferredSize(new Dimension(Stile.px(210),Stile.px(36)));come.addActionListener(a->{if(!silenzio){segna();Comportamento nuovo=(Comportamento)come.getSelectedItem();if(nuovo==Comportamento.PROGRESSIVO){try{Serie old=c.serie();int cif=old==null?3:old.cifre();c.serie(new Serie(valore.getText().trim(),cif));}catch(RuntimeException ex){c.comportamento(nuovo);}}else c.comportamento(nuovo);mostra(eti,e);cambiato();}});s.campo("Quando stampi",come);
        if(c.comportamento()==Comportamento.PROGRESSIVO){Serie serie=c.serie();if(serie!=null){CodiceView cv=new CodiceView(serie.prefisso(),serie.finestra(serie.prossimo()));cv.corpo(12);s.largo(cv);Integer[] valori=new Integer[9];for(int i=0;i<valori.length;i++)valori[i]=Integer.valueOf(i+1);final JComboBox<Integer> cifre=new JComboBox<Integer>(valori);cifre.setSelectedItem(Integer.valueOf(serie.cifre()));cifre.setFont(Stile.normale());cifre.setPreferredSize(new Dimension(Stile.px(82),Stile.px(34)));cifre.addActionListener(a->{if(!silenzio&&cifre.getSelectedItem()!=null){int v=((Integer)cifre.getSelectedItem()).intValue();segna();eti.cambiaFinestra(c.nome(),v);mostra(eti,e);cambiato();}});s.riga("Cifre che cambiano",cifre);s.nota("Solo la parte evidenziata aumenta. Il resto rimane uguale.");}else s.nota("Per il progressivo il codice deve terminare con almeno una cifra.");}else if(c.comportamento()==Comportamento.CHIESTO)s.nota("Il valore viene chiesto una volta prima del giro di stampa.");
        if(eti.elementiPerCampo(c).size()>1){Bottone indip=Bottone.normale("Usa un codice diverso");indip.setToolTipText("Scollega solo questo elemento dagli altri");indip.addActionListener(a->{if(!silenzio){segna();eti.rendiIndipendente(e);mostra(eti,e);cambiato();}});s.largo(indip);s.nota("Questo codice e' condiviso da "+NomiDati.uso(eti,c)+". Il QR conserva sempre il valore completo.");}return s;}
    private Component testo(final Elemento e){Scheda s=new Scheda("Testo");s.setAlignmentX(Component.LEFT_ALIGNMENT);s.riga("Allineamento",allineamento(e));s.riga("Righe",righe(e));final JCheckBox sep=new JCheckBox("Mostra punti e simboli",e.mostraSeparatori());sep.setOpaque(false);sep.setFont(Stile.piccolo());sep.setForeground(Stile.SUB1);sep.setFocusPainted(false);sep.addActionListener(a->{if(!silenzio){segna();e.mostraSeparatori(sep.isSelected());cambiato();}});s.largo(sep);s.nota("Se li nascondi, cambiano solo le scritte. QR e barcode conservano il codice esatto.");return s;}
    private Component allineamento(final Elemento e){JPanel p=gruppoCompatto();ButtonGroup g=new ButtonGroup();String[] nomi={"Sinistra","Centro","Destra"};for(int i=0;i<nomi.length;i++){final int v=i;JToggleButton b=scelta(nomi[i],e.allineamento()==i);b.addActionListener(a->{if(!silenzio){segna();e.allineamento(v);cambiato();}});g.add(b);p.add(b);}return p;}
    private Component righe(final Elemento e){JPanel p=gruppoCompatto();ButtonGroup g=new ButtonGroup();String[] nomi={"Auto","1","2","3"};int corrente=e.righePreferite();for(int i=0;i<nomi.length;i++){final int v=i;JToggleButton b=scelta(nomi[i],corrente==i);b.addActionListener(a->{if(!silenzio){segna();e.righePreferite(v);e.massimoRighe(3);cambiato();}});g.add(b);p.add(b);}return p;}
    private Component lettura(final Etichetta eti,final Elemento e){Scheda s=new Scheda("QR");s.setAlignmentX(Component.LEFT_ALIGNMENT);JComboBox<Correzione> livello=new JComboBox<Correzione>(Correzione.values());livello.setSelectedItem(e.correzione());livello.setFont(Stile.normale());livello.setPreferredSize(new Dimension(Stile.px(120),Stile.px(34)));livello.addActionListener(a->{if(!silenzio){segna();e.correzione((Correzione)livello.getSelectedItem());mostra(eti,e);cambiato();}});s.riga("Robustezza",livello);String contenuto=eti.contenuto(e,0);int lato;try{lato=Qr.codifica(contenuto,e.correzione()).length;}catch(RuntimeException ex){s.largo(new Stato("QR non valido",Stile.ROSSO,Stile.PESCA_SOFT));s.nota(ex.getMessage());return s;}double modulo=e.larghezza()/lato,q=4*modulo;boolean quiet=e.x()>=q&&e.y()>=q&&eti.larghezza()-e.x()-e.larghezza()>=q&&eti.altezza()-e.y()-e.larghezza()>=q;if(modulo>=.25&&quiet)s.largo(new Stato("Pronto da leggere",Stile.VERDE,Stile.VERDE_SOFT));else if(modulo<.25){s.largo(new Stato("Ingrandisci il QR",Stile.PESCA,Stile.PESCA_SOFT));s.nota("Trascina una maniglia blu verso l'esterno.");}else{s.largo(new Stato("Serve piu' spazio bianco",Stile.PESCA,Stile.PESCA_SOFT));s.nota("Allontana il QR dai bordi o dagli altri elementi.");}if(mostraPrecisione){s.riga("Matrice",etichettina(lato+" x "+lato));s.riga("Modulo",etichettina(mm(modulo)));}return s;}
    private Component barre(final Etichetta eti,final Elemento e){Scheda s=new Scheda("Barcode");s.setAlignmentX(Component.LEFT_ALIGNMENT);String contenuto=eti.contenuto(e,0);try{int mod=Code128.moduli(contenuto);double m=e.larghezza()/mod;s.largo(new Stato(m>=.25?"Pronto da leggere":"Allarga il barcode",m>=.25?Stile.VERDE:Stile.PESCA,m>=.25?Stile.VERDE_SOFT:Stile.PESCA_SOFT));if(mostraPrecisione){s.riga("Formato",etichettina("Code 128"));s.riga("Barra minima",etichettina(mm(m)));}}catch(RuntimeException ex){s.largo(new Stato("Contenuto non valido",Stile.ROSSO,Stile.PESCA_SOFT));s.nota(ex.getMessage());}return s;}
    private Component posizione(final Etichetta eti,final Elemento e){Scheda s=new Scheda("Sistema");s.setAlignmentX(Component.LEFT_ALIGNMENT);s.nota("Trascina per spostare. Trascina una maniglia blu per ridimensionare.");JPanel rot=gruppoCompatto();ButtonGroup gruppo=new ButtonGroup();int[] gradi={0,90,180,270};for(final int gr:gradi){JToggleButton b=scelta(gr+"°",e.rotazione()==gr);b.addActionListener(a->{if(!silenzio){segna();e.rotazione(gr);cambiato();}});gruppo.add(b);rot.add(b);}s.riga("Ruota",rot);JToggleButton precisione=scelta(mostraPrecisione?"Nascondi misure":"Misure precise",mostraPrecisione);precisione.addActionListener(a->{mostraPrecisione=precisione.isSelected();mostra(eti,e);});s.largo(precisione);if(mostraPrecisione){s.riga("X",misura(e.x(),0,eti.larghezza(),v->e.x(v)));s.riga("Y",misura(e.y(),0,eti.altezza(),v->e.y(v)));s.riga("Larghezza",misura(e.larghezza(),1,Math.max(eti.larghezza(),eti.altezza()),v->e.larghezza(v)));if(e.tipo()==Tipo.BARCODE||e.tipo()==Tipo.LINEA)s.riga("Altezza",misura(e.altezza(),.4,Math.max(eti.larghezza(),eti.altezza()),v->e.altezza(v)));if(e.tipo().scritto())s.riga("Testo",misura(e.corpo(),1,40,v->e.corpo(v)));}return s;}
    private interface Posa{void applica(double v);} private Component misura(final double val,final double min,final double max,final Posa p){JPanel r=new JPanel(new java.awt.BorderLayout(Stile.px(6),0));r.setOpaque(false);final JTextField f=new JTextField(numero(val),5);preparaCampo(f);f.setHorizontalAlignment(JTextField.RIGHT);JLabel unit=new JLabel("mm");unit.setFont(Stile.piccolo());unit.setForeground(Stile.SUB0);r.add(f,java.awt.BorderLayout.CENTER);r.add(unit,java.awt.BorderLayout.EAST);Runnable salva=new Runnable(){@Override public void run(){if(silenzio)return;try{double v=Double.parseDouble(f.getText().trim().replace(',','.'));v=Math.max(min,Math.min(max,v));segna();p.applica(v);f.setText(numero(v));cambiato();}catch(NumberFormatException ex){java.awt.Toolkit.getDefaultToolkit().beep();f.setText(numero(val));}}};f.addActionListener(a->salva.run());f.addFocusListener(new FocusAdapter(){@Override public void focusLost(FocusEvent e){salva.run();}});return r;}
    private static JPanel gruppoCompatto(){JPanel p=new JPanel(new FlowLayout(FlowLayout.RIGHT,Stile.px(3),0));p.setOpaque(false);return p;}
    private static JToggleButton scelta(String t,boolean selected){JToggleButton b=new JToggleButton(t);b.setFont(Stile.minuscolo());b.setSelected(selected);b.setFocusPainted(false);b.setMargin(new java.awt.Insets(Stile.px(5),Stile.px(7),Stile.px(5),Stile.px(7)));return b;}
    private static void preparaCampo(JTextField f){f.setFont(Stile.normale());f.setPreferredSize(new Dimension(f.getPreferredSize().width,Stile.px(34)));}
    private static JTextArea testoSecondario(String t){JTextArea a=new JTextArea(t);a.setEditable(false);a.setFocusable(false);a.setOpaque(false);a.setLineWrap(true);a.setWrapStyleWord(true);a.setFont(Stile.piccolo());a.setForeground(Stile.SUB0);a.setAlignmentX(Component.LEFT_ALIGNMENT);a.setColumns(24);a.setRows(2);Dimension d=a.getPreferredSize();a.setPreferredSize(new Dimension(Stile.px(245),d.height));a.setMaximumSize(new Dimension(Integer.MAX_VALUE,d.height));return a;}
    private static String valoreVisibile(Campo c){return c.serie()!=null?c.serie().codice(c.serie().prossimo()):c.valore();}
    private void applicaValore(Etichetta eti,Elemento e,Campo c,JTextField f){String v=f.getText().trim();try{segna();if(c.comportamento()==Comportamento.PROGRESSIVO){int n=c.serie()==null?3:c.serie().cifre();c.serie(new Serie(v,n));}else c.valore(v);cambiato();}catch(RuntimeException ex){f.setToolTipText(ex.getMessage());java.awt.Toolkit.getDefaultToolkit().beep();}}
    private static JLabel etichettina(String s){JLabel l=new JLabel(s);l.setFont(Stile.normale());l.setForeground(Stile.TESTO);return l;}private static String numero(double v){return String.valueOf(Math.round(v*10.0)/10.0).replace('.',',');}private static String mm(double v){return String.valueOf(Math.round(v*100)/100.0).replace('.',',')+" mm";}
    private void segna(){if(!silenzio&&prima!=null)prima.run();}private void cambiato(){if(dopo!=null)dopo.run();}
    private static final class CampoRenderer extends DefaultListCellRenderer{private final Etichetta eti;CampoRenderer(Etichetta e){eti=e;}@Override public Component getListCellRendererComponent(JList<?> list,Object value,int index,boolean sel,boolean focus){super.getListCellRendererComponent(list,value,index,sel,focus);if(value instanceof Campo)setText(NomiDati.nome(eti,(Campo)value));return this;}}
    private static final class Badge extends JLabel{private final Color bg,border;Badge(String t,Color bg,Color border){super(t.toUpperCase());this.bg=bg;this.border=border;setFont(Stile.minuscolo().deriveFont(java.awt.Font.BOLD));setForeground(border);setBorder(BorderFactory.createEmptyBorder(3,7,3,7));}@Override protected void paintComponent(Graphics g){Graphics2D g2=Stile.liscio(g);try{Stile.riquadro(g2,0,0,getWidth(),getHeight(),Stile.px(7),bg,border);}finally{g2.dispose();}super.paintComponent(g);}}
    private static final class Stato extends JLabel{private final Color c,bg;Stato(String t,Color c,Color bg){super("●  "+t);this.c=c;this.bg=bg;setFont(Stile.piccolo().deriveFont(java.awt.Font.BOLD));setForeground(c);setBorder(BorderFactory.createEmptyBorder(7,9,7,9));}@Override protected void paintComponent(Graphics g){Graphics2D g2=Stile.liscio(g);try{Stile.riquadro(g2,0,0,getWidth(),getHeight(),Stile.px(8),bg,null);}finally{g2.dispose();}super.paintComponent(g);}}
}
