package app.stile;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.border.Border;

/** Shared application styling; color is reserved for status and action meaning. */
public final class Stile {
    private Stile(){}
    public static final Color CRUST=new Color(0xD9DEE8),MANTLE=new Color(0xE8ECF3),BASE=new Color(0xF4F6FA),S0=new Color(0xD2D8E3),S1=new Color(0xBEC7D5),TESTO=new Color(0x283246),SUB1=new Color(0x4B5870),SUB0=new Color(0x66738A),OV1=new Color(0x8792A6),OV0=new Color(0x9CA7B8),BLU=new Color(0x2563EB),LAVANDA=new Color(0x665CF6),VERDE=new Color(0x16803C),ROSSO=new Color(0xC93648),PESCA=new Color(0xE66A25),CELESTE=new Color(0x0F8FA8),VERDE_SOFT=new Color(0xE7F6EC),VERDE_BORDO=new Color(0xA7D9B6),BLU_SOFT=new Color(0xEAF1FF),PESCA_SOFT=new Color(0xFFF1E8),LAVANDA_SOFT=new Color(0xF0EEFF),BANCO=new Color(0xDDE2EA),CARTA=Color.WHITE,INCHIOSTRO=new Color(0x111827);
    private static float base=12f;private static String famiglia=Font.SANS_SERIF;
    public static void installaLookAndFeel(){try{for(UIManager.LookAndFeelInfo info:UIManager.getInstalledLookAndFeels())if("Nimbus".equals(info.getName())){UIManager.setLookAndFeel(info.getClassName());return;}UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());}catch(Exception ignorata){}}
    public static void adottaFontDiSistema(){Font f=UIManager.getFont("Label.font");if(f!=null&&f.getSize2D()>=8f&&f.getSize2D()<=40f)base=f.getSize2D();famiglia=Font.SANS_SERIF;configuraSwing();}
    private static void configuraSwing(){Font n=normale(),p=piccolo();Border field=BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(S1),BorderFactory.createEmptyBorder(px(5),px(8),px(5),px(8)));UIManager.put("Panel.background",BASE);UIManager.put("Label.foreground",TESTO);UIManager.put("Label.font",n);UIManager.put("TextField.font",n);UIManager.put("TextField.background",Color.WHITE);UIManager.put("TextField.foreground",TESTO);UIManager.put("TextField.caretForeground",BLU);UIManager.put("TextField.selectionBackground",new Color(0xCFE0FF));UIManager.put("TextField.border",field);UIManager.put("FormattedTextField.font",n);UIManager.put("FormattedTextField.background",Color.WHITE);UIManager.put("FormattedTextField.border",field);UIManager.put("ComboBox.font",n);UIManager.put("ComboBox.background",Color.WHITE);UIManager.put("ComboBox.foreground",TESTO);UIManager.put("ComboBox.padding",new Insets(px(4),px(6),px(4),px(6)));UIManager.put("Button.font",n);UIManager.put("Button.margin",new Insets(px(5),px(9),px(5),px(9)));UIManager.put("ToggleButton.font",n);UIManager.put("ToggleButton.margin",new Insets(px(5),px(8),px(5),px(8)));UIManager.put("CheckBox.font",n);UIManager.put("CheckBox.foreground",TESTO);UIManager.put("Spinner.font",n);UIManager.put("Spinner.background",Color.WHITE);UIManager.put("TabbedPane.font",forte());UIManager.put("TabbedPane.background",BASE);UIManager.put("TabbedPane.foreground",SUB1);UIManager.put("TabbedPane.selected",Color.WHITE);UIManager.put("ScrollPane.border",BorderFactory.createEmptyBorder());UIManager.put("ScrollBar.width",Integer.valueOf(px(12)));UIManager.put("ToolTip.font",p);UIManager.put("ToolTip.background",TESTO);UIManager.put("ToolTip.foreground",Color.WHITE);UIManager.put("ToolTip.border",BorderFactory.createEmptyBorder(px(5),px(7),px(5),px(7)));UIManager.put("OptionPane.messageFont",n);UIManager.put("OptionPane.buttonFont",n);}
    public static float corpoBase(){return base;}public static int px(double a12){return(int)Math.round(a12*base/12.0);}public static Font font(double corpo,int stile){return new Font(famiglia,stile,Math.max(1,(int)Math.round(corpo*base/12.0)));}public static Font minuscolo(){return font(10.5,Font.PLAIN);}public static Font piccolo(){return font(11.5,Font.PLAIN);}public static Font normale(){return font(13,Font.PLAIN);}public static Font forte(){return font(13,Font.BOLD);}public static Font titolo(){return font(17,Font.BOLD);}public static Font mono(double corpo){return new Font(Font.MONOSPACED,Font.PLAIN,Math.max(1,(int)Math.round(corpo*base/12.0)));}
    public static Color tinta(Color c,double k){k=Math.max(0,Math.min(1,k));return new Color((int)Math.round(c.getRed()+(255-c.getRed())*k),(int)Math.round(c.getGreen()+(255-c.getGreen())*k),(int)Math.round(c.getBlue()+(255-c.getBlue())*k));}
    public static Graphics2D liscio(Graphics g){Graphics2D g2=(Graphics2D)g.create();g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,RenderingHints.VALUE_TEXT_ANTIALIAS_ON);g2.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL,RenderingHints.VALUE_STROKE_PURE);return g2;}
    public static void riquadro(Graphics2D g,int x,int y,int w,int h,int r,Color dentro,Color bordo){if(dentro!=null){g.setColor(dentro);g.fillRoundRect(x,y,w,h,r,r);}if(bordo!=null){g.setColor(bordo);g.drawRoundRect(x,y,w-1,h-1,r,r);}}
}
