package prove;

import app.archivio.Formato;
import app.modello.*;
import app.render.Ingombri;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.file.Files;

public final class ProvaRelease {
    private static int ok, ko;
    public static void main(String[] args) throws Exception { multiData(); roundTrip(); undoRedo(); settings(); rotations(); System.out.println(ok + " behavior checks, " + ko + " failed"); if (ko != 0) System.exit(1); }
    private static Etichetta sample() { Etichetta e=new Etichetta("Produzione",50,30); Campo a=new Campo("codice",Comportamento.PROGRESSIVO,"A-001");a.serie(new Serie("A-001",3));Campo b=new Campo("codice 2",Comportamento.PROGRESSIVO,"B-0900");b.serie(new Serie("B-0900",4));Campo lotto=new Campo("lotto",Comportamento.CHIESTO,"L-44");e.aggiungi(a).aggiungi(b).aggiungi(lotto);e.aggiungi(new Elemento("QR",Tipo.QR,"codice",3,3,12));Elemento testo=new Elemento("Testo",Tipo.CODICE,"codice",18,3,25);testo.allineamento(1);testo.mostraSeparatori(false);testo.righePreferite(3);testo.rotazione(270);e.aggiungi(testo);e.aggiungi(new Elemento("QR 2",Tipo.QR,"codice 2",3,17,10));e.aggiungi(new Elemento("Lotto",Tipo.TESTO,"lotto",18,18,25));return e; }
    private static void multiData(){Etichetta e=sample();check("two independent progressives are retained",e.progressivi().size()==2);check("shared QR and text remain one data source",e.elementiPerCampo(e.campo("codice")).size()==2);check("first progressive starts at A-001","A-001".equals(e.valoreAllaCopia(e.campo("codice"),0)));check("second progressive starts at B-0900","B-0900".equals(e.valoreAllaCopia(e.campo("codice 2"),0)));check("both progressives validate one run",valid(e,12));e.consumaProgressivi(12);check("first progressive advances independently","A-013".equals(e.campo("codice").corrente()));check("second progressive advances independently","B-0912".equals(e.campo("codice 2").corrente()));Elemento text=e.elementi().get(1);Campo independent=e.rendiIndipendente(text);check("make independent creates another data id",independent!=null&&!"codice".equals(independent.nome()));check("original source is now used only once",e.elementiPerCampo(e.campo("codice")).size()==1);}
    private static boolean valid(Etichetta e,int copies){try{e.validaGiro(copies);return true;}catch(RuntimeException ex){return false;}}
    private static void roundTrip(){Etichetta e=sample();e.consumaProgressivi(7);String text=Formato.scrivi(e);Etichetta r=Formato.leggi(text);check("storage round-trip keeps both progressives",r.progressivi().size()==2);check("storage round-trip keeps first counter","A-008".equals(r.campo("codice").corrente()));check("storage round-trip keeps second counter","B-0907".equals(r.campo("codice 2").corrente()));check("storage round-trip keeps shared links",r.elementiPerCampo(r.campo("codice")).size()==2);Elemento t=r.elementi().get(1);check("storage keeps centered text",t.allineamento()==1);check("storage keeps hidden separators",!t.mostraSeparatori());check("storage keeps explicit three-line layout",t.righePreferite()==3);check("storage keeps 270 degree rotation",t.rotazione()==270);String v3="etichette-custom\t3\nnome\tVecchia\nmisura\t50\t30\ncampo\tc\tFISSO\tABC.123\t\t\nelemento\tTesto\tCODICE\tc\t2\t2\t40\t40\t4\t0\t0\t3\tM\t1\t0\n";Etichetta old=Formato.leggi(v3);check("v3 labels still load",old.elementi().size()==1);check("v3 labels default to automatic line layout",old.elementi().get(0).righePreferite()==0);}
    private static void undoRedo(){Etichetta e=sample();Storia s=new Storia();s.segna(e);double before=e.elementi().get(0).x();e.elementi().get(0).x(before+5);check("undo is available after a recorded edit",s.qualcosaDaAnnullare());check("undo restores geometry",s.annulla(e)&&Math.abs(e.elementi().get(0).x()-before)<.001);check("redo becomes available",s.qualcosaDaRipetere());check("redo reapplies geometry",s.ripeti(e)&&Math.abs(e.elementi().get(0).x()-(before+5))<.001);}
    private static void settings() throws Exception {String old=System.getProperty("user.home");File home=Files.createTempDirectory("etichette-settings-").toFile();try{System.setProperty("user.home",home.getAbsolutePath());Impostazioni a=new Impostazioni();a.cartellaEtichette(new File(home,"layout lungo reparto A"));a.cartellaLog(new File(home,"registro turno serale"));a.stampante("Datamax test");a.risoluzioneDpi(300);a.salva();Impostazioni b=new Impostazioni();check("settings persist printer","Datamax test".equals(b.stampante()));check("settings persist dpi",b.risoluzioneDpi()==300);check("settings persist label path",b.cartellaEtichette().getName().equals("layout lungo reparto A"));check("settings persist log path",b.cartellaLog().getName().equals("registro turno serale"));}finally{if(old!=null)System.setProperty("user.home",old);}}
    private static void rotations(){Etichetta e=new Etichetta("Rotazioni",60,40);e.aggiungi(new Campo("c",Comportamento.FISSO,"HELLO-12345"));Elemento t=new Elemento("Codice",Tipo.CODICE,"c",10,10,25).corpo(5,false);e.aggiungi(t);BufferedImage im=new BufferedImage(800,600,BufferedImage.TYPE_INT_ARGB);Graphics2D g=im.createGraphics();try{t.rotazione(0);Rectangle2D.Double b0=Ingombri.di(g,e,t,10,0);t.rotazione(90);Rectangle2D.Double b90=Ingombri.di(g,e,t,10,0);t.rotazione(180);Rectangle2D.Double b180=Ingombri.di(g,e,t,10,0);t.rotazione(270);Rectangle2D.Double b270=Ingombri.di(g,e,t,10,0);check("90 degree hitbox swaps width and height",near(b0.width,b90.height)&&near(b0.height,b90.width));check("180 degree hitbox keeps visible size",near(b0.width,b180.width)&&near(b0.height,b180.height));check("270 degree hitbox swaps width and height",near(b0.width,b270.height)&&near(b0.height,b270.width));check("rotated hitboxes stay anchored to visible top-left",near(b0.x,b90.x)&&near(b0.y,b90.y));}finally{g.dispose();}}
    private static boolean near(double a,double b){return Math.abs(a-b)<.05;}private static void check(String name,boolean condition){if(condition){ok++;System.out.println("  ok   "+name);}else{ko++;System.out.println("  FAIL "+name);}}
}
